language: ruby
rvm:
- 2.3.3
script: bundle exec rake
before_script:
  - service postgresql status
  - psql -c 'create database smartcitizen-auth_test;' -U postgres
  - bundle exec rake db:migrate
  #- RAILS_ENV=test bundle exec rake db:migrate
services:
  - postgresql

env:
  global:
    - POSTGRES_HOST=localhost
