version: '3.3'

services:
  db:
    image: postgres
    #ports:
      #- '5432:5432'
    volumes:
      - sck_auth_db:/var/lib/postgresql/data

#  redis:
#    image: redis

  app:
    build: .
#   env_file: .env
    ports:
      - "3000:3000"
#   depends_on:
#      - db
#      - redis
    volumes:
      - "./:/app"
    command: rails server -p 3000 -b '0.0.0.0'
    environment:
      - DATABASE_URL=postgresql://db

#  sidekiq:
#    build: .
#    env_file: .env
#    depends_on:
#      - app
#      - redis
#    command: bundle exec sidekiq
volumes:
  sck_auth_db:
